version: '3'
services:
  todoback:
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database
    
  todofront:
    image: todofrontend
    restart: on-failure
    depends_on:
      - todoback
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront